### ISSUE TITLE
Failures thrown in the YAKS config scripts are not reported

### ISSUE THREAD

**Issue by bouskaJ** [citrusframework/yaks#236]
Errors thrown during YAKS config scripts are not reported in `yaks report command` tests are automatically skipped and there is no mention about that in the `yaks report` command output. This means that we can't rely on the yask report and we have to count feature files or manually go through every test log to check script errors.

```
➜  camel-k-example-basic git:(master) ✗ yaks test test      
Creating new test namespace yaks-c8aebb66-2c5a-410b-9891-ee066d460ef8
Unable to find existing YAKS operator - adding new operator instance to temporary namespace by default
Running integrations:
Error: unknown command "xx" for "kamel"
Failed to run integrations: 
exit status 1
AutoRemove namespace yaks-c8aebb66-2c5a-410b-9891-ee066d460ef8
Test results: Total: 0, Passed: 0, Failed: 0, Errors: 1, Skipped: 0

Errors: 1
[
  "Failed to run integrations: exit status 1"
]
Error: Failed to run integrations: exit status 1
➜  camel-k-example-basic git:(master) ✗ yaks report -o junit     
<?xml version="1.0" encoding="UTF-8"?><testsuites>
  <testsuite name="org.citrusframework.yaks.JUnitReport" errors="0" failures="0" skipped="0" tests="0" time="0"></testsuite>
</testsuites>
```

**Comment by bouskaJ** [comment]
@christophd can you improve the report feature?

**Comment by christophd** [comment]
I thought this has been already addressed with #152 and fixed with #208

it should be in version 0.2.0

**Comment by bouskaJ** [comment]
the example you can see was generated on the last released version (https://github.com/citrusframework/yaks/releases/tag/v0.2.0) is it supposed to be there or not yet?

**Comment by christophd** [comment]
yes it should be fixed in 0.2.0 

I have to revisit the fix and see why it is not working in your example then

**Comment by christophd** [comment]
So I have narrowed this down to the `yaks report -o junit` call

This call reads all json test results reported from the remote test pods. When the error is in the pre script then not pod is initialized and the result json file is not written to the local output.

The previous fix only writes the error results to the `junit-reports.xml` in the local output directly. So if you open that file after the test run you should see the errors. I need to also write the json test results so that `yaks report -o junit` also fetches the errors.

**Comment by bouskaJ** [comment]
Hi @christophd this is still not working as expected

```
reating new test namespace yaks-82ed2906-fb16-4368-aafc-b5eb72b6a6eb
Running ObtainToken:
/tmp/yaks-script-122414253.sh: line 5: throwError: command not found
Failed to run ObtainToken: 
exit status 127
AutoRemove namespace yaks-82ed2906-fb16-4368-aafc-b5eb72b6a6eb
Test results: Total: 0, Passed: 0, Failed: 0, Errors: 1, Skipped: 0
	 (.): Failure caused by InitializationError - Failed to run ObtainToken: exit status 127

Error: There are test failures!
➜  monitoring git:(main) ✗ yaks report -o junit
<?xml version="1.0" encoding="UTF-8"?><testsuites></testsuites>
```

```
yaks version        
YAKS 0.4.0-202105060009
```

```
config:
  namespace:
    temporary: true
pre:
  - name: ObtainToken
    run: throwError
```
```
